- hosts: webservers
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes
      become: yes

    - name: update index.html
      ansible.builtin.template:
        src: ./files/index2.html
        dest: "/usr/share/nginx/html/index.html"
      notify:
        - rest nginx
      become: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - rest nginx
      become: yes

  handlers:
    - name: rest nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes

