- hosts: webservers
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes

    - name: update nginx config
      ansible.builtin.copy:
        src: ./files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: 
        - rest nginx
      become: yes

    - name: update index.html
      ansible.builtin.copy:
        src: ./files/index.html
        dest: /usr/share/nginx/html/index.html
      notify: 
        - rest nginx
      become: yes


  handlers:
    - name: rest nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes

